[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CancelChain"
authors = [{name = "Thomas Bohmbach, Jr.", email = "tom@cancelchain.org"}]
dynamic = ["version", "description"]
